name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TITLE: true
          SHOW_TOTAL: true
          SHOW_PROJECTS: false
          SHOW_EDITORS: false
          SHOW_LANGUAGE_PER_REPO: false
          SHOW_TOTAL_CODE_TIME: true
          SHOW_PROFILE_VIEWS: false
